# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/stt.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/stt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/stt.proto\x12\x03stt\"7\n\x0c\x41udioRequest\x12\x15\n\raudio_content\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"G\n\x15TranscriptionResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"a\n\rStreamRequest\x12#\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x11.stt.StreamConfigH\x00\x12 \n\x05\x61udio\x18\x02 \x01(\x0b\x32\x0f.stt.AudioChunkH\x00\x42\t\n\x07payload\"e\n\x0cStreamConfig\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x15\n\rlanguage_code\x18\x02 \x01(\t\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\x12\x17\n\x0freturn_partials\x18\x04 \x01(\x08\"+\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0f\n\x07is_last\x18\x02 \x01(\x08\"m\n\x0eStreamResponse\x12)\n\x07partial\x18\x01 \x01(\x0b\x32\x16.stt.PartialTranscriptH\x00\x12%\n\x05\x66inal\x18\x02 \x01(\x0b\x32\x14.stt.FinalTranscriptH\x00\x42\t\n\x07payload\"4\n\x11PartialTranscript\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\tstability\x18\x02 \x01(\x02\"A\n\x0f\x46inalTranscript\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2\x83\x01\n\x03STT\x12;\n\nTranscribe\x12\x11.stt.AudioRequest\x1a\x1a.stt.TranscriptionResponse\x12?\n\x10TranscribeStream\x12\x12.stt.StreamRequest\x1a\x13.stt.StreamResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.stt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOREQUEST']._serialized_start=25
  _globals['_AUDIOREQUEST']._serialized_end=80
  _globals['_TRANSCRIPTIONRESPONSE']._serialized_start=82
  _globals['_TRANSCRIPTIONRESPONSE']._serialized_end=153
  _globals['_STREAMREQUEST']._serialized_start=155
  _globals['_STREAMREQUEST']._serialized_end=252
  _globals['_STREAMCONFIG']._serialized_start=254
  _globals['_STREAMCONFIG']._serialized_end=355
  _globals['_AUDIOCHUNK']._serialized_start=357
  _globals['_AUDIOCHUNK']._serialized_end=400
  _globals['_STREAMRESPONSE']._serialized_start=402
  _globals['_STREAMRESPONSE']._serialized_end=511
  _globals['_PARTIALTRANSCRIPT']._serialized_start=513
  _globals['_PARTIALTRANSCRIPT']._serialized_end=565
  _globals['_FINALTRANSCRIPT']._serialized_start=567
  _globals['_FINALTRANSCRIPT']._serialized_end=632
  _globals['_STT']._serialized_start=635
  _globals['_STT']._serialized_end=766
# @@protoc_insertion_point(module_scope)
