# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shared.protos import service_pb2 as shared_dot_protos_dot_service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shared/protos/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServiceStub(object):
    """==========================================
    1. LLM SERVICE (The Brain)
    Used by: Chat Service
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateResponse = channel.unary_unary(
                '/policy_app.LLMService/GenerateResponse',
                request_serializer=shared_dot_protos_dot_service__pb2.LLMRequest.SerializeToString,
                response_deserializer=shared_dot_protos_dot_service__pb2.LLMResponse.FromString,
                _registered_method=True)
        self.StreamResponse = channel.unary_stream(
                '/policy_app.LLMService/StreamResponse',
                request_serializer=shared_dot_protos_dot_service__pb2.LLMRequest.SerializeToString,
                response_deserializer=shared_dot_protos_dot_service__pb2.LLMResponse.FromString,
                _registered_method=True)


class LLMServiceServicer(object):
    """==========================================
    1. LLM SERVICE (The Brain)
    Used by: Chat Service
    ==========================================
    """

    def GenerateResponse(self, request, context):
        """Generates text based on prompt (and context)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamResponse(self, request, context):
        """Optional: If you want streaming text generation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateResponse,
                    request_deserializer=shared_dot_protos_dot_service__pb2.LLMRequest.FromString,
                    response_serializer=shared_dot_protos_dot_service__pb2.LLMResponse.SerializeToString,
            ),
            'StreamResponse': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamResponse,
                    request_deserializer=shared_dot_protos_dot_service__pb2.LLMRequest.FromString,
                    response_serializer=shared_dot_protos_dot_service__pb2.LLMResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'policy_app.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('policy_app.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService(object):
    """==========================================
    1. LLM SERVICE (The Brain)
    Used by: Chat Service
    ==========================================
    """

    @staticmethod
    def GenerateResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy_app.LLMService/GenerateResponse',
            shared_dot_protos_dot_service__pb2.LLMRequest.SerializeToString,
            shared_dot_protos_dot_service__pb2.LLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/policy_app.LLMService/StreamResponse',
            shared_dot_protos_dot_service__pb2.LLMRequest.SerializeToString,
            shared_dot_protos_dot_service__pb2.LLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RAGServiceStub(object):
    """==========================================
    2. RAG SERVICE (The Knowledge Base)
    Used by: Chat Service & API Gateway
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RetrieveContext = channel.unary_unary(
                '/policy_app.RAGService/RetrieveContext',
                request_serializer=shared_dot_protos_dot_service__pb2.SearchRequest.SerializeToString,
                response_deserializer=shared_dot_protos_dot_service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.TriggerSync = channel.unary_unary(
                '/policy_app.RAGService/TriggerSync',
                request_serializer=shared_dot_protos_dot_service__pb2.SyncRequest.SerializeToString,
                response_deserializer=shared_dot_protos_dot_service__pb2.SyncResponse.FromString,
                _registered_method=True)
        self.DeleteVectors = channel.unary_unary(
                '/policy_app.RAGService/DeleteVectors',
                request_serializer=shared_dot_protos_dot_service__pb2.DeleteVectorRequest.SerializeToString,
                response_deserializer=shared_dot_protos_dot_service__pb2.DeleteVectorResponse.FromString,
                _registered_method=True)
        self.GetVectors = channel.unary_unary(
                '/policy_app.RAGService/GetVectors',
                request_serializer=shared_dot_protos_dot_service__pb2.GetVectorRequest.SerializeToString,
                response_deserializer=shared_dot_protos_dot_service__pb2.GetVectorResponse.FromString,
                _registered_method=True)
        self.ListDocuments = channel.unary_unary(
                '/policy_app.RAGService/ListDocuments',
                request_serializer=shared_dot_protos_dot_service__pb2.Empty.SerializeToString,
                response_deserializer=shared_dot_protos_dot_service__pb2.ListDocsResponse.FromString,
                _registered_method=True)


class RAGServiceServicer(object):
    """==========================================
    2. RAG SERVICE (The Knowledge Base)
    Used by: Chat Service & API Gateway
    ==========================================
    """

    def RetrieveContext(self, request, context):
        """--- For Chat Flow ---
        Retrieves relevant text chunks for a query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerSync(self, request, context):
        """--- For Management Flow ---
        Triggers the worker to process a file (Async)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVectors(self, request, context):
        """Deletes vectors for a specific document
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVectors(self, request, context):
        """Debug/Management: Check vectors for a doc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RAGServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RetrieveContext': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveContext,
                    request_deserializer=shared_dot_protos_dot_service__pb2.SearchRequest.FromString,
                    response_serializer=shared_dot_protos_dot_service__pb2.SearchResponse.SerializeToString,
            ),
            'TriggerSync': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerSync,
                    request_deserializer=shared_dot_protos_dot_service__pb2.SyncRequest.FromString,
                    response_serializer=shared_dot_protos_dot_service__pb2.SyncResponse.SerializeToString,
            ),
            'DeleteVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVectors,
                    request_deserializer=shared_dot_protos_dot_service__pb2.DeleteVectorRequest.FromString,
                    response_serializer=shared_dot_protos_dot_service__pb2.DeleteVectorResponse.SerializeToString,
            ),
            'GetVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVectors,
                    request_deserializer=shared_dot_protos_dot_service__pb2.GetVectorRequest.FromString,
                    response_serializer=shared_dot_protos_dot_service__pb2.GetVectorResponse.SerializeToString,
            ),
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=shared_dot_protos_dot_service__pb2.Empty.FromString,
                    response_serializer=shared_dot_protos_dot_service__pb2.ListDocsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'policy_app.RAGService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('policy_app.RAGService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RAGService(object):
    """==========================================
    2. RAG SERVICE (The Knowledge Base)
    Used by: Chat Service & API Gateway
    ==========================================
    """

    @staticmethod
    def RetrieveContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy_app.RAGService/RetrieveContext',
            shared_dot_protos_dot_service__pb2.SearchRequest.SerializeToString,
            shared_dot_protos_dot_service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy_app.RAGService/TriggerSync',
            shared_dot_protos_dot_service__pb2.SyncRequest.SerializeToString,
            shared_dot_protos_dot_service__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy_app.RAGService/DeleteVectors',
            shared_dot_protos_dot_service__pb2.DeleteVectorRequest.SerializeToString,
            shared_dot_protos_dot_service__pb2.DeleteVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy_app.RAGService/GetVectors',
            shared_dot_protos_dot_service__pb2.GetVectorRequest.SerializeToString,
            shared_dot_protos_dot_service__pb2.GetVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy_app.RAGService/ListDocuments',
            shared_dot_protos_dot_service__pb2.Empty.SerializeToString,
            shared_dot_protos_dot_service__pb2.ListDocsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ChatServiceStub(object):
    """==========================================
    3. CHAT SERVICE (The Orchestrator)
    Used by: API Gateway (for /chat and /ws/chat)
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Interact = channel.unary_unary(
                '/policy_app.ChatService/Interact',
                request_serializer=shared_dot_protos_dot_service__pb2.ChatRequest.SerializeToString,
                response_deserializer=shared_dot_protos_dot_service__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.StreamAudioChat = channel.stream_stream(
                '/policy_app.ChatService/StreamAudioChat',
                request_serializer=shared_dot_protos_dot_service__pb2.AudioChunk.SerializeToString,
                response_deserializer=shared_dot_protos_dot_service__pb2.ChatStreamResponse.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """==========================================
    3. CHAT SERVICE (The Orchestrator)
    Used by: API Gateway (for /chat and /ws/chat)
    ==========================================
    """

    def Interact(self, request, context):
        """Standard Text Chat: Takes query, returns answer + citations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAudioChat(self, request_iterator, context):
        """Audio Streaming: Takes audio stream, returns text updates (transcription/answer)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Interact': grpc.unary_unary_rpc_method_handler(
                    servicer.Interact,
                    request_deserializer=shared_dot_protos_dot_service__pb2.ChatRequest.FromString,
                    response_serializer=shared_dot_protos_dot_service__pb2.ChatResponse.SerializeToString,
            ),
            'StreamAudioChat': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAudioChat,
                    request_deserializer=shared_dot_protos_dot_service__pb2.AudioChunk.FromString,
                    response_serializer=shared_dot_protos_dot_service__pb2.ChatStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'policy_app.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('policy_app.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """==========================================
    3. CHAT SERVICE (The Orchestrator)
    Used by: API Gateway (for /chat and /ws/chat)
    ==========================================
    """

    @staticmethod
    def Interact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy_app.ChatService/Interact',
            shared_dot_protos_dot_service__pb2.ChatRequest.SerializeToString,
            shared_dot_protos_dot_service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAudioChat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/policy_app.ChatService/StreamAudioChat',
            shared_dot_protos_dot_service__pb2.AudioChunk.SerializeToString,
            shared_dot_protos_dot_service__pb2.ChatStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
